WebProje/Controllers/BankAccountsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebProje.Data;
using WebProje.Models;

namespace WebProje.Controllers
{
    [Authorize]
    public class BankAccountsController : Controller
    {
        private readonly AppDbContext _context;

        public BankAccountsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: BankAccounts
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (this.User.IsInRole("Admin"))
            {
                var appDbContext = _context.BankAccounts.Include(b => b.Users);
                return View(await appDbContext.ToListAsync());
            }
            else
            {
                var appDbContext = _context.BankAccounts.Include(b => b.Users).Where(x => x.UsersId == userId);
                return View(await appDbContext.ToListAsync());

            }
            // return View(await appDbContext.ToListAsync());
        }

        // GET: BankAccounts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccounts
                .Include(b => b.Users)
                .FirstOrDefaultAsync(m => m.BankAccountID == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // GET: BankAccounts/Create
        public IActionResult Create()
        {
            ViewData["UsersId"] = new SelectList(_context.Users, "Id", "UserName");
            List<String> tyeps = new List<String>();
            tyeps.Add("Euro");
            tyeps.Add("Tl");
            tyeps.Add("Dolar");
            ViewBag.tyeps = tyeps;

            return View();
        }

        // POST: BankAccounts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BankAccountID,BankAccountName,BankAccountType,BankAccountBalance,BankAccountLimit,UsersId")] BankAccount bankAccount)
        {
            if (ModelState.IsValid)
            {


                if (this.User.IsInRole("Admin"))
                {
                    _context.Add(bankAccount);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                    bankAccount.UsersId = userId;
                    _context.Add(bankAccount);
                    await _context.SaveChangesAsync();
                    return Redirect("~/Home/Index");
                }
            }


            return View(bankAccount);
        }

        // GET: BankAccounts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccounts.FindAsync(id);
            if (bankAccount == null)
            {
                return NotFound();
            }
            ViewData["UsersId"] = new SelectList(_context.Users, "Id", "Name", bankAccount.UsersId);
            return View(bankAccount);
        }

        // POST: BankAccounts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BankAccountID,BankAccountName,BankAccountType,BankAccountBalance,BankAccountLimit,UsersId")] BankAccount bankAccount)
        {
            if (id != bankAccount.BankAccountID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    if (this.User.IsInRole("Admin"))
                    {
                        _context.Update(bankAccount);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                        bankAccount.UsersId = userId;
                        _context.Update(bankAccount);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BankAccountExists(bankAccount.BankAccountID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (this.User.IsInRole("Admin"))
                {
                    return Redirect("~/BankAccounts/Index");
                }
                else
                {
                    return Redirect("~/Home/Index");
                }
            }
            ViewData["UsersId"] = new SelectList(_context.Users, "Id", "Id", bankAccount.UsersId);
            return View(bankAccount);
        }

        // GET: BankAccounts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bankAccount = await _context.BankAccounts
                .Include(b => b.Users)
                .FirstOrDefaultAsync(m => m.BankAccountID == id);
            if (bankAccount == null)
            {
                return NotFound();
            }

            return View(bankAccount);
        }

        // POST: BankAccounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bankAccount = await _context.BankAccounts.FindAsync(id);
            _context.BankAccounts.Remove(bankAccount);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BankAccountExists(int id)
        {
            return _context.BankAccounts.Any(e => e.BankAccountID == id);
        }
    }
}

WebProje/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebProje.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebProje.Areas.Identity.Data;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebProje.Data;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Http;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace WebProje.Controllers
{
    [Authorize]

    public class HomeController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly AppDbContext _Appcontext;
        private readonly ILogger<HomeController> _logger;
        private readonly UserManager<Users> _userManager;
        public HomeController(ILogger<HomeController> logger, DatabaseContext context, UserManager<Users> userManager, AppDbContext Appcontext)
        {
            _logger = logger;
            _context = context;
            _userManager = userManager;
            _Appcontext = Appcontext;
        }
        [Authorize]
        public IActionResult Index()
        {
            //Current User Or Admin
            var allusers = _Appcontext.Users.ToList();
            ViewBag.allusers = allusers;
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var currentUser = _Appcontext.Users.FirstOrDefault(u => u.Id == userId);
            ViewBag.User = currentUser;
            ViewBag.allusers = allusers;


            //Viewbag user bills
           ViewBag.userbills= _Appcontext.Bills.Where(u => u.UsersId == userId).ToList();


            // Sum Money for Customer
            List<BankAccount> bankacccounts = _Appcontext.BankAccounts.Where(x => x.UsersId == userId).ToList();
            var sum_amounts = 0.0;
            foreach (var item in bankacccounts)
            {
                sum_amounts = sum_amounts + item.BankAccountBalance;
            }
            ViewBag.sumAmounts = sum_amounts;


            List<Bill> bills;
            // Total Bİll 
            if (this.User.IsInRole("Admin"))
            {

                bills = _Appcontext.Bills.Include(b => b.Users).ToList();
            }
            else
            {
                bills = _Appcontext.Bills.Where(x => x.UsersId == userId).ToList();

            }

            ViewBag.bills = bills;
            var unpayed_sum_bills = 0.0;
            var payed_sum_bills = 0.0;
            foreach (var item in bills)
            {
                if (item.BillStatus == false)
                {
                    unpayed_sum_bills += item.BillAmount;
                }
                else
                {
                    payed_sum_bills += item.BillAmount;

                }

            }
            ViewBag.unpayed_sum_bills = unpayed_sum_bills;
            ViewBag.payed_sum_bills = payed_sum_bills;

            //Add position
            var staffs = _Appcontext.Staffs.ToList();

            ViewBag.staffs = staffs;

            //Bank money
            var bankMoney = _Appcontext.Banks.FirstOrDefault().BankMoney;
            ViewBag.bankMoney = bankMoney;
            return View(bankacccounts);
        }
        /*  [HttpPost]
          public IActionResult Cookie(string culture)
          {
              Response.Cookies.Append
                  (
                  CookieRequestCultureProvider.DefaultCookieName,
                  CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                      new CookieOptions
                      {
                          Expires = DateTimeOffset.Now.AddDays(10)
                      }
                      );



              return RedirectToAction("Index");
          }*/


        //public IActionResult ChangeLanguage(string culture)
        //{
        //    Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName,
        //        CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
        //        new CookieOptions() { Expires = DateTimeOffset.UtcNow.AddYears(1) });

        //    return Redirect(Request.Headers["Referer"].ToString());
        //}

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Accounts()
        {

            return View();
        }
    }
}

WebProje/Views/Home/Index.cshtml
@model List<WebProje.Models.BankAccount>
@using Microsoft.AspNetCore.Identity
@using WebProje.Models
@{ ViewData["Title"] = "Home Page"; }
@inject SignInManager<Users> SignInManager
@inject UserManager<Users> UserManager
@using Microsoft.Extensions.Localization;
@inject IStringLocalizer<lang> lang
<!-- Sale & Revenue Start -->
<head>


    <style type="text/css">
        * {
            margin: 0;
            padding: 0;
            font-family: "Roboto", sans-serif;
        }

        body {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            background-color: #34495e;
        }

        .cards {
            width: 100%;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
        }

        .card {
            margin: 40px;
            position: relative;
            max-width: 250px;
            max-height: 350px;
            box-shadow: 0 40px 60px -6px black;
        }

        .card-title {
            display: block;
            text-align: center;
            color: #fff;
            background-color: #6184a8;
            padding: 2%;
            border-top-right-radius: 4px;
            border-top-left-radius: 4px;
        }

        .card img {
            width: 100%;
            height: 98%;
            object-fit: cover;
            display: block;
            position: relative;
            -webkit-filter: grayscale(100%);
        }

        .card-desc {
            display: block;
            font-size: 1.2rem;
            position: absolute;
            height: 0;
            top: 0;
            opacity: 0;
            padding: 18px 8%;
            background-color: darkred;
            transition: 0.8s ease;
        }

        .card:hover .card-desc {
            opacity: 0.9;
            height: 100%;
        }

        h1 {
            font-size: 2.8rem;
            color: #fff;
            margin: 40px 0 20px 0;
            text-align: center;
        }
    </style>

</head>
@**@
@ViewBag.bill
<div class="container-fluid pt-4 px-4">
    <div class="row g-4 d-flex justify-content-between">
        @if (this.User.IsInRole("Admin"))
        {<div class="col-sm-6 col-xl-3">
                <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                    <i class="fa fa-chart-line fa-3x text-primary"></i>
                    <div class="ms-3">
                        <p class="mb-2">@lang["Bank Money"]</p>
                        <h6 class="mb-0">@ViewBag.bankMoney</h6>
                    </div>
                </div>
            </div>
            }

        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-line fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">@lang["Total Balance"]</p>
                    <h6 class="mb-0">@ViewBag.sumAmounts</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-bar fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">@lang["Pending Payments"]</p>
                    <h6 class="mb-0">@ViewBag.unpayed_sum_bills</h6>
                </div>
            </div>
        </div>
        <div class="col-sm-6 col-xl-3">
            <div class="bg-secondary rounded d-flex align-items-center justify-content-between p-4">
                <i class="fa fa-chart-area fa-3x text-primary"></i>
                <div class="ms-3">
                    <p class="mb-2">@lang["Payed Bill"]</p>
                    <h6 class="mb-0">@ViewBag.payed_sum_bills</h6>
                </div>
            </div>
        </div>

    </div>
</div>

@if (User.Identity.IsAuthenticated)
{
<div class="container-fluid pt-4 px-4">
    <div class="row g-4">
        @foreach (var item in Model)
        {@*<div class="col-sm-12 col-xl-6">
                    <div class="bg-secondary text-center rounded p-4">
                        <div class="d-flex align-items-center justify-content-between mb-4">
                            <h6 class="mb-0">Accounts</h6>
                            <a href="">Show All</a>
                        </div>
                        <div class="container-fluid">
                            <div class="card p-2 m-2 d-inline-block d-grid bg-danger">

                                <div class="card-body">
                                    <h5 class="card-title text-dark">@item.BankAccountName</h5>
                                    <h7 class="card-text"> @item.BankAccountBalance </h7>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>*@}
        <!--Card try-->
        <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

        <div class="cards">
            @foreach (var item in Model)
            {
<div class="card ">
    <h2 class="card-title">@item.BankAccountType</h2>
    <img src="https://cdn2.iconfinder.com/data/icons/shopping-e-commerce-1-1/32/Wallet-Balance-money-Cash-Account-512.png" alt="">

    <div class=" card-desc w-100   ">

        <h5 class="card-title text-dark">@item.BankAccountName</h5>
        <div class=" d-felx align-items-center">
            <h5>Balance</h5>
            <h7 class="card-text  "> @item.BankAccountBalance</h7>
            <a asp-controller="BankAccounts" asp-action="Edit" asp-route-id="@item.BankAccountID">Edit</a> |
            <a asp-controller="BankAccounts" asp-action="Details" asp-route-id="@item.BankAccountID">Details</a> |
        </div>
    </div>
</div>          }

        </div>

        <!--Card try -->
    </div>
</div>}
<!-- Sales Chart End -->

<div class="container-fluid pt-4 px-4">

    <div class="bg-secondary text-center rounded p-4">

        <div class="d-flex align-items-center justify-content-between mb-4">
            <h6 class="mb-0">@lang["Bills"]</h6>
            <a href="">@lang["Show All"]</a>
        </div>
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-white">
                        <th scope="col"><input class="form-check-input" type="checkbox"></th>
                        <th scope="col">@lang["Date"]</th>
                        <th scope="col">@lang["Customer"]</th>
                        <th scope="col">@lang["Amount"]</th>
                        <th scope="col">@lang["Status"]</th>
                        <th scope="col">@lang["Description"]</th>
                    </tr>
                </thead>
                <tbody>
                    @if (User.Identity.IsAuthenticated)
                    {
        @if (this.User.IsInRole("Admin"))
        {
@foreach (var item in ViewBag.allusers)
{
    if (item.Bills != null)
    {
        foreach (var bills in item.Bills)
        {
<tr>
    <td><input class="form-check-input" type="checkbox"></td>
    <td>@bills.BillDate</td>
    <td>@item.Name</td>
    <td>@bills.BillAmount</td>
    <td>@bills.BillStatus</td>
    <td>@bills.BillDesc</td>
    <td>
        @if (bills.BillStatus == true)
        {
<a class="">Payed</a> }
else
{
<a class="">UnPayed</a>}
    </td>
</tr>}
                        }

                    } }

else
{
if (ViewBag.User != null & ViewBag.userbills != null)
{

@foreach (var item in ViewBag.userbills)
{

<tr>
    <td><input class="form-check-input" type="checkbox"></td>
    <td>@item.BillDate</td>
    <td>@ViewBag.User.Name</td>
    <td>@item.BillAmount</td>
    <td>@item.BillStatus</td>
    <td>@item.BillDesc</td>
    <td>
        @if (@item.BillStatus == false)
        {
<a class="btn btn-sm btn-primary" href="/Bills/Pay/@item.BillID">Pay</a> }
else
{
<a class="btn btn-sm btn-primary" href="/Bills/Details/@item.BillID">Detail</a>}
    </td>
</tr>
}}
}}







                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Recent Sales End -->
<!-- Widgets Start -->
<div class="container-fluid pt-4 px-4">
    <div class="row g-4 d-flex justify-content-between">
        <div class="col-sm-12 col-md-6 col-xl-4">
            <div class="h-100 bg-secondary rounded p-4">
                <div class="d-flex align-items-center justify-content-between mb-2">
                    <h6 class="mb-0">Messages</h6>
                    <a href="">Show All</a>
                </div>
                @foreach (var staff in ViewBag.staffs)
                {
    <div class="d-flex align-items-center border-bottom py-3">
        <img class="rounded-circle flex-shrink-0" src="img/user.jpg" alt="" style="width: 40px; height: 40px;">
        <div class="w-100 ms-3">
            <div class="d-flex w-100 justify-content-between">
                @{TimeSpan time = (Convert.ToDateTime(DateTime.Now) - Convert.ToDateTime(staff.AddTime));}
                <h6 class="mb-0">@staff.FullName</h6>
                <small>@time.Days.ToString() days @time.Hours.ToString() hours @time.Minutes.ToString() min ago </small>


            </div>

            <span>New @staff.Position added</span>

        </div>

    </div>}




            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-xl-4">
            <div class="h-100 bg-secondary rounded p-4">
                <div class="d-flex align-items-center justify-content-between mb-4">
                    <h6 class="mb-0">@lang["Calender"]</h6>
                    <a href="">@lang["Show All"]</a>
                </div>
                <div id="calender"></div>
            </div>
        </div>

    </div>
</div>
<!-- Widgets End -->